### ISSUE TITLE
Rulebook Content Improvements

### ISSUE THREAD

**Issue by calda** [gtgreekweek/Greek-Week-Calendar#11]
- [x] Show a spinner in the modal while waiting for the rulebook content to load
- [x] Add some mechanism to specify a different rulebook lookup name than the event name itself (for example, "Red Cross Blood Drive" would show the "Greek Week Philanthropy Rules" section)

**Comment by dbecker1** [comment]
Completed in d48429a1437468aee1912b144ab83afce9bd0a5c

**Comment by calda** [comment]
Thanks @dbecker1!
