### ISSUE TITLE
Display list of events

### ISSUE THREAD

**Issue by calda** [gtgreekweek/Greek-Week-Calendar#4]
For this week, set up the page so that it can display a list of event objects as described in [this issue](https://github.com/gtgreekweek/Greek-Week-Calendar/issues/2) that @dbecker1 will be working on.

It's important to include some mechanism that will allow the user to filter events based on tags. Also, it would be nice if we could define specific colors for each tag, and style them like GitHub labels.

I can draw up a wireframe if you want, but otherwise you're free to design it as you see fit.

**Comment by ChangedNameTo** [comment]
Added in a set of tags along with filter buttons to show and hide any events by tag. Works on both desktop and mobile.
