### ISSUE TITLE
Replace Jekyll templating with Javascript rendering

### ISSUE THREAD

**Issue by calda** [gtgreekweek/Greek-Week-Calendar#5]
Since we're fetching the info from a spreadsheet, we've outgrown simple Jekyll templating. We can replace the Jekyll system with some sort of Javascript setup that presumably just maps an array of `Event` objects to an array of DOM elements. Do it however you want.

**Comment by dbecker1** [comment]
Added dynamic rendering and removed jekyll in 3543d0bbbe5c3d429d77ff117588165dced6531f. I used a templating engine called Mustache to simplify things. The spreadsheet that it is loading from can be found here: 

https://docs.google.com/spreadsheets/d/16xMR7wsN4MetV1v1qKoGqIqv2ucDih2OdC6bB3Lwf88/edit?usp=sharing

**Comment by calda** [comment]
Very nice, thanks!
