### ISSUE TITLE
Bug fixes and small improvements

### ISSUE THREAD

**Issue by calda** [gtgreekweek/Greek-Week-Calendar#6]
Making some good progress on this site!

Small things we talked about during the meeting:
- [x] Fix the Filter events slide down on small devices. Since the slide-down is kinda wonky (especially once the user has scrolled down), I think it might be better to just use a modal. That sounds more appropriate for mobile devices.
 - [x] Add a time label to the event cards. The visual weight should be a little less than the date, but not by much.
 - [x] Only let the user filter by one tag at a time. When the tag is selected the user should see events with that tag.
 - [x] Add a some sort of "View Rules" button to the event card. When clicked, it'll open a modal that @dbecker1 is working on.
 - [x] Add a "Filter Events" title to the sidebar (on desktop), and don't show the horizontal separators. I also think it would look good if the sidebar has the same visual styling as the cards (white background, rounded corners, drop shadow, etc).

**Comment by ChangedNameTo** [comment]
#12

**Comment by ChangedNameTo** [comment]
#
