### ISSUE TITLE
Add "Upcoming Events" and "Past Events"

### ISSUE THREAD

**Issue by calda** [gtgreekweek/Greek-Week-Calendar#7]
We want the site to distinguish between "Upcoming Events" and "Past Events". We should preserve the continuity of the event timeline, but insert some sort of "Upcoming Events" header at the point where they switch from being in the past to in the future.

When the user opens the page, it should automatically scroll to the "Upcoming Events" header. To see Past Events, they'd need to scroll up.

Since this relies on dynamic javascript rendering, this is dependent on @dbecker1 finishing #5.

**Comment by ChangedNameTo** [comment]
There was no good way to use a header that wouldn't conflict with the other styling on the page, however I was able to add in the auto scrolling

Merged in #13
